[tool.poetry]
name = "async-requester"
version = "0.1.0"
description = ""
authors = ["luceroquispe <Lucero.Quispe@proton.me>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
